### ISSUE TITLE
Features at the top of footprint are mirrored

### ISSUE THREAD

**Issue by alexandertoresson** [Gumball2415/NES-Famicom-Cartridge-Dimensions#1]
Hi,

Thanks for an excellent footprint! Unfortunately, I found a mistake: the two small plastic supports, 0.85mm in radius, and the end of the part of the plastic where you grab the cartridge, are mirrored. By mirroring them on the x axis they become correct.

**Comment by Gumball2415** [comment]
which footprint are you referring to?

**Comment by alexandertoresson** [comment]
Sorry, I'm referring to NES-EWROM-01, here's an illustration of what's mirrored:
![ewrom-mirrored](https://github.com/Gumball2415/NES-Famicom-Cartridge-Dimensions/assets/104172/bd1f4423-5df9-4f84-a353-a16e797ab45f)
